spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/java-basics?retryWrites=true

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.adarsh.learning: DEBUG